theme = "docuapi"
themesdir = "themes"
languageCode = "en-us"
baseurl = "http://docs.status.im"
title = "Status Developer Documentation"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "en"

[params]
search = true
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "js"
name = "Javascript"
# [[params.language_tabs]]
# key = "cljs"
# name = "Clojurescript"
# [[params.language_tabs]]
# key = "go"
# name = "Go" 
# [[params.language_tabs]]
# key = "shell"
# name = "Shell" 
# [[params.language_tabs]]
# key = "ruby"
# name = "Ruby"
# [[params.language_tabs]]
# key = "python"
# name = "Python"


#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "Status Developer Documentation"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"Android: <a href='http://test.status.im'>Download</a>, <a href='http://artifacts.status.im:8081/artifactory/nightlies-local/'>Nightlies</a>",
"iOS: Testflight invite required",
"-------",
"<a href='https://hackathon.status.im'>Enter our Hackathon</a>",
"<a href='https://wiki.status.im'>Read the Wiki</a>",
"<a href='http://slack.status.im'>Join our Slack</a>",
"<a href='https://github.com/status-im/docs.status.im'>Edit this Documentation</a>",
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true
