theme = "docuapi"
themesdir = "themes"
languageCode = "en-us"
baseurl = "http://docs.status.im"
title = "Status Developer Documentation"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "en"

[params]
search = true
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "js"
name = "Javascript"
[[params.language_tabs]]
key = "cljs"
name = "Clojurescript"
# [[params.language_tabs]]
# key = "go"
# name = "Go" 
# [[params.language_tabs]]
# key = "shell"
# name = "Shell" 
# [[params.language_tabs]]
# key = "ruby"
# name = "Ruby"
# [[params.language_tabs]]
# key = "python"
# name = "Python"


#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "Status Developer Documentation"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='#'>Sign Up for a Developer Key</a>",
"Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme by [bep](https://github.com/bep)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true
